
export const users = [
  {
    id: 1,
    name: "Chiara",
    surname: "Maggio",
    username: "magichiara",
    email: "info.chiaramaggio@gmail.com",
    pic: "https://randomuser.me/api/portraits/women/1.jpg",
    password: "coding",
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    favorite: [],
  },
  {
    id: 2,
    name: "Cesare",
    surname: "Tomasello",
    username: "cesare28",
    email: "cesare.tomasello@outlook.com",
    pic: "https://randomuser.me/api/portraits/men/1.jpg",
    password: "coding",
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    favorite: [],
  },
  {
    id: 3,
    name: "Marco",
    surname: "Rivera",
    username: "marcoriv",
    email: "marcorivera.dev@gmail.com",
    pic: "https://randomuser.me/api/portraits/men/1.jpg",
    password: "coding",
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    favorite: [],
  },
  {
    id: 4,
    name: "Pietro",
    surname: "Di Stefano",
    username: "pietro23",
    email: "pietrodistefano2306@gmail.com",
    pic: "https://randomuser.me/api/portraits/men/1.jpg",
    password: "coding",
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    favorite: [],
  },
  {
    id: 5,
    name: "Sebastiano",
    surname: "Occhipinti",
    username: "sebastiano25",
    email: "sebastianoocchipinti25@gmail.com ",
    pic: "https://randomuser.me/api/portraits/men/1.jpg",
    password: "coding",
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    favorite: [],
  },
];
